### ISSUE TITLE
Distance calculation incorrect

### ISSUE THREAD

**Issue by Stivo** [grumlimited/geocalc#1]
The distance calculation is only correct for small distances.

	import com.grum.geocalc.*;

	public class Bug {
		public static void main(String[] args) {
			//Kew, London
			Coordinate lat = new DegreeCoordinate(51.4843774);
			Coordinate lng = new DegreeCoordinate(-0.2912044);
			Point kew = new Point(lat, lng);

			//Buenos Aires, as per wolframalpha.com
			lat = new DegreeCoordinate(34.61);
			lng = new DegreeCoordinate(-58.37);
			Point richmond = new Point(lat, lng);

			double distance = EarthCalc.getDistance(richmond, kew); //in meters	
			System.out.println(distance);
		}
	}

As you can see in wolframalpha.com, it is supposed to be more than 11000 Km.
http://www.wolframalpha.com/input/?i=buenos+aires+to+london

**Comment by gr211** [comment]
Added Vicenty for distance calculation in v0.4.
