### ISSUE TITLE
Publish in Maven Central Repo

### ISSUE THREAD

**Issue by hectorespert** [grumlimited/geocalc#13]
Have you thought about publishing the library to Maven's central repository?
I think it is a problem when using the library in a project.

I can help you publish it and automate it with travis.

**Comment by gr211** [comment]
Hi @blackleg 

This could be a good thing indeed. Never bothered really but it might expose this libraty to a greater number.

I suppose before doing that, I'd need to remove the dep on log4j and make it dependant on slf4j instead.

How can I let you help me achieve that ? Same excuse as everyone I guess, I'm lacking the time to look into this (ie. maven repo) properly.

Thanks for offering your help.

**Comment by blackleg** [comment]
We publish some libraries in maven central repo, for example: https://github.com/peertopark/java-commons

One question, Have you a email with the grum.com domain?

**Comment by blackleg** [comment]
@gr211 About log4j dependency see [pull/14](https://github.com/grumlimited/geocalc/pull/14)

**Comment by gr211** [comment]
hi @blackleg i have resorted to using jitpack instead. Could not really be bothered witn maven central at this point.

**Comment by blackleg** [comment]
@gr211 Good work. 
It seems good to me but in my opinion should be published in a future in the maven central repo.

**Comment by gr211** [comment]
@blackleg about an email for the gum domain, actually that would be rgallet at grumlimited.co.uk
