### ISSUE TITLE
Allow users to use geocalc through Jitpack

### ISSUE THREAD

**Issue by pierrelemee** [grumlimited/geocalc#15]
I wanted to suggest you to update the readme to offer developers to use geocalc through Jitpack.io

You can see that [the project is already available](https://jitpack.io/#grumlimited/geocalc/v0.5.1) so it might ease the integration process for developers, and for you avoid the culprit of submitting the project on Maven central.

I tried it on one of my local project, and it worked smoothly. You did a great job guys ;)

**Comment by gr211** [comment]
thanks a lot @pierrelemee for the suggestion.
