### ISSUE TITLE
Rounding issue in calculation of spherical law of cosines

### ISSUE THREAD

**Issue by dusiema** [grumlimited/geocalc#24]
I think I found a rounding issue in calculation of spherical law of cosines. 

I have created a pull request for it (accompanied by  unit-test) which sould explain this: 

https://github.com/grumlimited/geocalc/pull/23

**Comment by gr211** [comment]
Many thanks @dusiema. I have just requested a small change to your PR.

**Comment by gr211** [comment]
Merged in 0.5.7.
