### ISSUE TITLE
the variable should be Radius. 

### ISSUE THREAD

**Issue by pradeepmurugesan** [grumlimited/geocalc#25]
The line here mentions the variable as EARTH_DIAMETER
https://github.com/grumlimited/geocalc/blob/master/src/main/java/com/grum/geocalc/EarthCalc.java#L44.

But as per the [wiki](https://en.wikipedia.org/wiki/Earth_radius#Fixed_radius) the value corresponds to radius. Also as per the [formula](https://en.wikipedia.org/wiki/Great-circle_distance) we should multiply with the radius.

**Comment by gr211** [comment]
Thanks @pradeepmurugesan . Changed in 0.5.8
