### ISSUE TITLE
Version 0.5.8 not published

### ISSUE THREAD

**Issue by Darker7** [grumlimited/geocalc#27]
You are advertising version 0.5.8 but did not publish it on jitpack.

See for yourself:
* [0.5.7 link](https://jitpack.io/com/github/grumlimited/geocalc/0.5.7/)
* [0.5.8 link](https://jitpack.io/com/github/grumlimited/geocalc/0.5.8/)
* ~~[master link](https://jitpack.io/com/github/grumlimited/geocalc/master/)~~

You've forgotten to create the '0.5.8' tag :Ü™

**Comment by gr211** [comment]
Fixed. Thx.
