### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Darker7** [grumlimited/geocalc#28]
It seems you have memorized the spelling of haversine incorrectly.

You spell it: haRvesine
While the correct spelling is: haveRsine

Here the [wikipedia entry](https://en.wikipedia.org/wiki/Haversine_formula) and [a dictionary entry](https://www.merriam-webster.com/dictionary/haversine) as source :Ü™

**Comment by gr211** [comment]
Thanks. Changed in 0.6
