### ISSUE TITLE
Bearing calculation incorrect

### ISSUE THREAD

**Issue by zhuyuping** [grumlimited/geocalc#3]
standpoint is 31.194326398628462:121.42127048962534
forepoint is 31.194353394639606:121.4212814985147

bearing is  340.76940494442715 

 but the correct result is 19.213575108209017

**Comment by gr211** [comment]
could you please retry v0.3.1?

i get 19.230595055572852D, and so does http://www.movable-type.co.uk/scripts/latlong.html.

could you let me know how you got to  19.213575108209017 ?
